'use strict';
const ROLL_DURATION=.48,ROLL_FRAMES=6;
const canvas=document.getElementById('world'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id), keys=new Set(), images={};
let W=0,H=0,scale=1,camera={x:768,y:510},last=0,time=0,paused=false,over=false,toastTime=8,stick={x:0,y:0},player,enemies,particles=[],slash=0,shake=0;
function inPolygon(x,y,polygon){let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a[1]>y)!=(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
function terrainPoint(x,y){const terrain=boarding?boardingTerrain:mountainLayouts[currentLevel];return terrain.areas.some(area=>inPolygon(x,y,area))&&!terrain.blockers.some(area=>inPolygon(x,y,area));}
function valid(x,y){return [[0,0],[8,0],[-8,0],[0,8],[0,-8]].every(([dx,dy])=>terrainPoint(x+dx,y+dy));}
function clearTerrainLine(ax,ay,bx,by){const steps=Math.ceil(Math.hypot(bx-ax,by-ay)/10);for(let i=0;i<=steps;i++){const t=steps?i/steps:0;if(!terrainPoint(ax+(bx-ax)*t,ay+(by-ay)*t))return false;}return true;}
function reset(){swordAudio.stop();const terrain=mountainLayouts[currentLevel];player={x:terrain.spawn[0],y:terrain.spawn[1],hp:100,sp:100,dir:0,face:{x:0,y:1},inv:0,cool:0,roll:0,rollDir:0,rollFace:{x:0,y:1},walk:0,gold:0,attack:0,attackHit:false,attackDir:0,wind:0,windCool:0,windPulse:0};const level=islands[currentLevel],positions=terrain.enemies;enemies=positions.slice(0,level.scouts).map(([x,y])=>({x,y,max:level.scoutHP,hp:level.scoutHP,home:{x,y}}));const [bossX,bossY]=terrain.boss;enemies.push({x:bossX,y:bossY,max:level.bossHP,hp:level.bossHP,home:{x:bossX,y:bossY},boss:true});enemies=enemies.map(e=>({...e,spriteType:level.enemyType,dir:0,attack:0,attackHit:false,attackDir:0,cool:1,flash:0,walk:0}));particles=[];over=false;paused=false;slash=0;keys.clear();stick={x:0,y:0};$('overlay').hidden=true;$('campaign').hidden=true;victoryPending=false;$('chapter-number').textContent='CHAPTER 0'+(currentLevel+1);$('island-name').textContent=level.name;$('quest-region').textContent=level.region;notify(level.name+' · Defeat '+level.scouts+' scouts, then challenge '+level.captain+'.',7);updateHud();}
function notify(text,duration=4){$('toast').textContent=text;toastTime=duration;$('toast').style.opacity=1;}
function direction(x,y){return Math.abs(x)>Math.abs(y)?(x<0?2:3):(y<0?1:0);}
function move(entity,dx,dy){const ox=entity.x,oy=entity.y;if(valid(entity.x+dx,entity.y))entity.x+=dx;if(valid(entity.x,entity.y+dy))entity.y+=dy;const distance=Math.hypot(entity.x-ox,(entity.y-oy)/.75);if(distance>.01){entity.moving=true;entity.dir=direction(entity.x-ox,entity.y-oy);entity.walk+=distance/90*Math.PI*2;}}
function attack(){if(paused||over||player.cool>0||player.roll>0)return;if(player.sp<18){notify('Recover stamina before attacking.',2);return;}player.sp-=18;player.cool=.48;player.attack=.48;player.attackHit=false;player.attackDir=player.dir;swordAudio.play();updateHud();}
function resolvePlayerHit(){slash=.16;let hit=false;for(const e of enemies){if(e.hp<=0||(e.boss&&enemies.some(other=>!other.boss&&other.hp>0)))continue;const dx=e.x-player.x,dy=e.y-player.y,d=Math.hypot(dx,dy);if(d<105&&clearTerrainLine(player.x,player.y,e.x,e.y)&&(dx*player.face.x+dy*player.face.y)/Math.max(1,d)>-.25){e.hp=Math.max(0,e.hp-28);e.flash=.22;hit=true;for(let i=0;i<9;i++)particles.push({x:e.x,y:e.y-28,vx:(Math.random()-.5)*160,vy:-Math.random()*120,t:.5,color:'#ffd481'});if(e.hp===0){player.gold+=e.boss?100:25;player.hp=Math.min(100,player.hp+12);if(e.boss){if(boarding){finishBoarding(true);return;}completeIsland();}else notify('Scout defeated. +25 gold · +12 health',4);}}}if(hit)shake=4;updateHud();}
function dodge(){if(paused||over||player.roll>0||player.sp<30)return;player.sp-=30;player.attack=0;swordAudio.stop();let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+stick.x,y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+stick.y;const mag=Math.hypot(x,y);player.rollFace=mag>.08?{x:x/mag,y:y/mag}:{...player.face};player.rollDir=direction(player.rollFace.x,player.rollFace.y);player.dir=player.rollDir;player.face={...player.rollFace};player.roll=ROLL_DURATION;player.inv=ROLL_DURATION;updateHud();}
function interact(){if(paused||over)return;if(enemies.some(e=>e.hp>0)){notify('Defeat all scouts and the captain to conquer this island.',3);return;}openCampaign();}
function updateHud(){updateWhirlwindHud();if(boarding){updateBoardingHud();return;}const level=islands[currentLevel],killed=enemies.filter(e=>!e.boss&&e.hp<=0).length,boss=enemies.find(e=>e.boss);$('hp').style.width=player.hp+'%';$('sp').style.width=player.sp+'%';$('stats').textContent=Math.ceil(player.hp)+' / 100 HP';$('coins').textContent=player.gold+' gold';$('quest').textContent=killed<level.scouts?'Defeat the '+level.scouts+' '+level.enemyName.toLowerCase()+'.':boss.hp>0?'Defeat '+level.captain+'.':'Island conquered. Open the sea chart to sail.';$('progress').textContent=killed<level.scouts?killed+' / '+level.scouts+' scouts defeated':boss.hp>0?'Captain · '+Math.ceil(boss.hp)+' / '+boss.max+' HP':conquered+' / 4 islands conquered';}
function showModal(kicker,title,text,button='Continue adventure'){swordAudio.stop();$('modalKicker').textContent=kicker;$('modalTitle').textContent=title;$('modalText').textContent=text;$('resume').textContent=button;$('overlay').hidden=false;paused=true;keys.clear();stick={x:0,y:0};}
function togglePause(){if(voyage&&!boarding)return;if(!$('campaign').hidden){closeCampaign();return;}if(over)return;if(paused){paused=false;$('overlay').hidden=true;}else showModal(islands[currentLevel].name.toUpperCase(),'Adventure paused','Defeat the scouts and captain to unlock the next island.');}
function tick(dt){time+=dt;if(paused)return;updateWhirlwind(dt);if(paused)return;player.moving=false;if(player.attack>0){player.attack=Math.max(0,player.attack-dt);if(player.attack<=.24&&!player.attackHit){player.attackHit=true;resolvePlayerHit();}}if(paused)return;for(const e of enemies)e.moving=false;player.cool=Math.max(0,player.cool-dt);player.inv=Math.max(0,player.inv-dt);player.roll=Math.max(0,player.roll-dt);slash=Math.max(0,slash-dt);shake=Math.max(0,shake-dt*25);player.sp=Math.min(100,player.sp+dt*16);let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+stick.x,dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+stick.y;if(player.attack>0){dx=0;dy=0;}const mag=Math.hypot(dx,dy);if(mag>.08&&player.roll<=0){dx/=Math.max(1,mag);dy/=Math.max(1,mag);player.face={x:dx/Math.hypot(dx,dy),y:dy/Math.hypot(dx,dy)};player.dir=direction(dx,dy);}if(player.roll>0){dx=player.rollFace.x;dy=player.rollFace.y;const progress=1-player.roll/ROLL_DURATION,speed=90+420*Math.sin(Math.PI*progress);move(player,dx*dt*speed,dy*dt*speed*.75);player.dir=player.rollDir;}else move(player,dx*dt*185,dy*dt*140);
const scoutsAlive=enemies.some(e=>!e.boss&&e.hp>0);
for(const e of enemies){if(e.hp<=0)continue;e.cool=Math.max(0,e.cool-dt);e.flash=Math.max(0,e.flash-dt);let x=player.x-e.x,y=player.y-e.y,d=Math.hypot(x,y);if(e.attack<=0)e.dir=direction(x,y);if(e.boss&&scoutsAlive)continue;if(e.attack>0){e.attack=Math.max(0,e.attack-dt);if(e.attack<=.25&&!e.attackHit){e.attackHit=true;const facing=[{x:0,y:1},{x:0,y:-1},{x:-1,y:0},{x:1,y:0}][e.attackDir];if(d<76&&clearTerrainLine(e.x,e.y,player.x,player.y)&&(x*facing.x+y*facing.y)/Math.max(1,d)>-.25&&player.inv<=0){player.hp=Math.max(0,player.hp-(e.boss?22+islands[currentLevel].damage:12+islands[currentLevel].damage));player.inv=.7;shake=7;notify(e.boss?'Captain strike! Dodge the red warning circle.':'Hit! Dodge with Space or the dodge button.',2);if(player.hp<=0){if(boarding){finishBoarding(false);return;}over=true;showModal('TRY AGAIN','Washed ashore','Your adventure isn’t over. Restart the island and time your dodges.','Restart island');}}e.cool=e.boss?1.5:1.8;}continue;}if(d<250&&clearTerrainLine(e.x,e.y,player.x,player.y)){if(d>57){move(e,x/d*dt*(e.boss?82:70),y/d*dt*(e.boss?63:54));}else if(e.cool<=0){e.attack=.9;e.attackDir=e.dir;e.attackHit=false;}}else {let hx=e.home.x+Math.sin(time*.5+e.home.x)*23-e.x,hy=e.home.y+Math.cos(time*.5+e.home.y)*14-e.y;move(e,hx*dt*.5,hy*dt*.5);}}
particles=particles.filter(p=>(p.t-=dt)>0);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=dt*220;}if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').style.opacity=0;}updateHud();}
function screen(x,y){return {x:(x-camera.x)*scale+W/2,y:(y-camera.y)*scale+H/2};}
function sprite(e,type){if(e!==player)type=e.spriteType||'pirate';const newEnemy=['raider','corsair','guard'].includes(type);const p=screen(e.x,e.y),size=(e.boss?87:71)*scale,bob=0;ctx.save();ctx.globalAlpha=e.inv>0&&!(e===player&&e.roll>0)&&Math.floor(time*15)%2?.45:1;ctx.fillStyle='#122d3475';ctx.beginPath();ctx.ellipse(p.x,p.y,17*scale,7*scale,0,0,Math.PI*2);ctx.fill();const rolling=e===player&&e.roll>0;const casting=e===player&&e.wind>0&&!rolling;const attacking=(e.attack>0||casting)&&!rolling;const walking=e.moving&&!(e===player&&e.roll>0)&&!attacking;const attackElapsed=(e===player?.48:.9)-e.attack;const attackFrame=casting?Math.min(3,Math.floor((1.1-e.wind)/1.1*4)):e===player?(attackElapsed<.12?0:attackElapsed<.24?1:attackElapsed<.34?2:3):(attackElapsed<.5?0:attackElapsed<.65?1:attackElapsed<.76?2:3);const gaitFrame=newEnemy?Math.floor((e.walk/(Math.PI*2)*4)%4):Math.floor((e.walk/(Math.PI*2)*6)%6);const mirrorNewAttack=attacking&&e.attackDir===2&&(type==='guard'||(type==='corsair'&&attackFrame===3));const attackDirection=casting?e.windDir:mirrorNewAttack?3:e.attackDir;const rollFrame=Math.min(ROLL_FRAMES-1,Math.floor((1-e.roll/ROLL_DURATION)*ROLL_FRAMES));let im=rolling?images['hero_roll_'+e.rollDir+'_'+rollFrame]:attacking?images[type+'_attack_'+attackDirection+'_'+attackFrame]:walking?images[type+'_walk_'+e.dir+'_'+gaitFrame]:images[type+'_'+e.dir];if(im){ctx.translate(p.x,p.y);if(mirrorNewAttack||(attacking&&!newEnemy&&attackDirection===2&&attackFrame===3))ctx.scale(-1,1);if(e.flash>0)ctx.filter='brightness(1.8)';if(type==='hero'&&!walking&&!attacking&&!rolling){/* The idle sheet's next row begins below y=138. Exclude its pirate hat. */ctx.drawImage(im,11,0,138,138,-size/2,-size+7*scale,size,size);}else{const drawSize=rolling?size*.67584:attacking?size*1.6:size;ctx.drawImage(im,-drawSize/2,-drawSize+7*scale+bob,drawSize,drawSize);}ctx.filter='none';}ctx.restore();if(e!==player){ctx.fillStyle='#082b35';ctx.fillRect(p.x-23*scale,p.y-size-9*scale,46*scale,5*scale);ctx.fillStyle=e.boss?'#f2bd66':'#f17a65';ctx.fillRect(p.x-23*scale,p.y-size-9*scale,46*scale*e.hp/e.max,5*scale);if(e.boss){ctx.font=`600 ${12*scale}px sans-serif`;ctx.textAlign='center';ctx.fillStyle='#fff3d4';ctx.fillText(boarding?'Captain Blackwake':islands[currentLevel].captain,p.x,p.y-size-16*scale);}}}
function render(){ctx.clearRect(0,0,W,H);scale=Math.max(W/1536,H/1024)*1.3;const viewW=W/scale,viewH=H/scale;camera.x=Math.max(viewW/2,Math.min(1536-viewW/2,player.x));camera.y=Math.max(viewH/2,Math.min(1024-viewH/2,player.y));ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);const origin=screen(0,0);ctx.drawImage(images[boarding?'boarding_deck':'island_'+currentLevel],origin.x,origin.y,1536*scale,1024*scale);for(const e of enemies){if(e.hp<=0||e.attack<=.25)continue;const p=screen(e.x,e.y);ctx.fillStyle='#f24b4250';ctx.strokeStyle='#ff625c';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y,78*scale,47*scale,0,0,Math.PI*2);ctx.fill();ctx.stroke();}
if(!boarding&&!enemies.some(e=>e.hp>0)){const p=screen(...mountainLayouts[currentLevel].spawn);ctx.strokeStyle='#fff2ae';ctx.fillStyle='#f3cd5b33';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,(28+Math.sin(time*3)*4)*scale,16*scale,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font=`600 ${14*scale}px sans-serif`;ctx.fillStyle='#fff3bd';ctx.textAlign='center';ctx.fillText('SET SAIL · E',p.x,p.y-40*scale);}
[...enemies.filter(e=>e.hp>0),player].sort((a,b)=>a.y-b.y).forEach(e=>sprite(e,e===player?'hero':'pirate'));
if(slash>0){const p=screen(player.x,player.y-20),a=Math.atan2(player.face.y*.7,player.face.x);ctx.save();ctx.translate(p.x,p.y);ctx.scale(scale,scale*.7);ctx.strokeStyle='#fff4ca';ctx.lineWidth=7;ctx.shadowColor='#ffd979';ctx.shadowBlur=18;ctx.beginPath();ctx.arc(0,0,76,a-1.1,a+1.1);ctx.stroke();ctx.restore();}
drawWhirlwind();for(const p of particles){const s=screen(p.x,p.y);ctx.globalAlpha=p.t*2;ctx.fillStyle=p.color;ctx.fillRect(s.x,s.y,4*scale,4*scale);}ctx.globalAlpha=1;ctx.restore();}
function frame(ts){const dt=Math.min(.04,(ts-last)/1000||.016);last=ts;if(paused||over||(voyage&&!boarding))swordAudio.stop();const walkBefore=player.walk,wasRolling=player.roll>0;tick(dt);footsteps.update((player.walk-walkBefore)*90/(Math.PI*2),!paused&&!over&&(!voyage||boarding)&&!wasRolling&&player.roll<=0&&player.attack<=0&&!(player.wind>0)&&player.moving);render();requestAnimationFrame(frame);}
function resize(){W=innerWidth;H=innerHeight;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}addEventListener('resize',resize);
addEventListener('keydown',e=>{let k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='j')attack();if(k==='k')whirlwind();if(k===' ')dodge();if(k==='e')interact();if(k==='escape')togglePause();if(k==='m'&&!e.repeat)openCampaign();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();stick={x:0,y:0};if(!paused&&!over)togglePause();});
$('whirlwind').onpointerdown=e=>{e.preventDefault();whirlwind();};$('attack').onpointerdown=e=>{e.preventDefault();attack();};$('dodge').onpointerdown=e=>{e.preventDefault();dodge();};$('interact').onclick=interact;$('pause').onclick=togglePause;$('help').onclick=()=>showModal('HOW TO PLAY','Make your first voyage','Move with WASD or arrow keys. Press J to slash, K for a magical whirlwind (40 stamina, 5-second cooldown), Space to roll, and E or M to open the sea chart after a conquest. On mobile, use the joystick and action buttons. Red circles warn of incoming attacks.');$('resume').onclick=()=>{if(victoryPending){openCampaign();return;}if(player.hp<=0)reset();else {paused=false;over=false;$('overlay').hidden=true;}};$('restart').onclick=reset;
let joyId=null;const joy=$('joystick');function joyMove(e){if(e.pointerId!==joyId)return;const r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,m=Math.max(36,Math.hypot(dx,dy));stick={x:dx/m,y:dy/m};$('stick').style.transform=`translate(${stick.x*32}px,${stick.y*32}px)`;}joy.onpointerdown=e=>{joyId=e.pointerId;joy.setPointerCapture(joyId);joyMove(e);};joy.onpointermove=joyMove;function joyEnd(){joyId=null;stick={x:0,y:0};$('stick').style.transform='';}joy.onpointerup=joyEnd;joy.onpointercancel=joyEnd;
async function load(name,path){images[name]=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Could not load '+path));im.src=path;});}
Promise.all([load('boarding_deck','assets/naval/boarding-deck.png'),...[0,1,2,3].flatMap(dir=>Array.from({length:ROLL_FRAMES},(_,f)=>load('hero_roll_'+dir+'_'+f,'assets/roll/hero_'+dir+'_'+f+'.png'))),load('player_ship','assets/naval/player-ship.png'),load('enemy_ship','assets/naval/enemy-ship.png'),load('battle_ocean','assets/naval/ocean.png'),...['raider','corsair','guard'].flatMap(type=>[0,1,2,3].flatMap(dir=>[load(type+'_'+dir,'assets/enemies/'+type+'/idle_'+dir+'.png'),...Array.from({length:4},(_,f)=>load(type+'_walk_'+dir+'_'+f,'assets/enemies/'+type+'/walk_'+dir+'_'+f+'.png')),...Array.from({length:4},(_,f)=>load(type+'_attack_'+dir+'_'+f,'assets/enemies/'+type+'/attack_'+dir+'_'+f+'.png'))])),...islands.map((island,i)=>load('island_'+i,island.image)),...[0,1,2,3].flatMap(i=>[load('hero_'+i,'assets/hero_'+i+'.png'),load('pirate_'+i,'assets/pirate_'+i+'.png'),...Array.from({length:4},(_,f)=>[load('hero_attack_'+i+'_'+f,'assets/attack/hero_'+i+'_'+f+'.png'),load('pirate_attack_'+i+'_'+f,'assets/attack/pirate_'+i+'_'+f+'.png')]).flat(),...Array.from({length:6},(_,f)=>[load('hero_walk_'+i+'_'+f,'assets/walk/hero_'+i+'_'+f+'.png'),load('pirate_walk_'+i+'_'+f,'assets/walk/pirate_'+i+'_'+f+'.png')]).flat()])]).then(()=>{resize();reset();$('loading').remove();if(conquered>0)openCampaign();requestAnimationFrame(frame);}).catch(()=>{$('loading').textContent='Island artwork could not load. Refresh to try again.';});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_adventure_state',description:'Read player health, stamina and island mission progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({ready:!!player,health:player?.hp,stamina:player?.sp,gold:player?.gold,remainingEnemies:enemies?.filter(e=>e.hp>0).length,island:islands[currentLevel].name,conqueredIslands:conquered,paused})})).catch(()=>{});}catch{}}

function whirlwind(){
 if(!player||paused||over||player.roll>0||player.wind>0)return;
 if(player.windCool>0){notify('Whirlwind recharging · '+Math.ceil(player.windCool)+'s',1.5);return;}
 if(player.sp<40){notify('Whirlwind needs 40 stamina.',2);return;}
 player.sp-=40;player.windDir=player.dir;player.wind=1.1;player.windCool=5;player.windPulse=0;notify('Whirlwind!',1);updateHud();
}
function updateWhirlwind(dt){
 player.windCool=Math.max(0,(player.windCool||0)-dt);if(!player.wind)return;
 player.wind=Math.max(0,player.wind-dt);const elapsed=1.1-player.wind;
 while(player.windPulse<3&&elapsed>=[.15,.45,.75][player.windPulse]){
  player.windPulse++;const protectedBoss=enemies.some(e=>!e.boss&&e.hp>0);
  for(const e of enemies){
   if(e.hp<=0||(e.boss&&protectedBoss)||Math.hypot(e.x-player.x,(e.y-player.y)/.75)>145||!clearTerrainLine(player.x,player.y,e.x,e.y))continue;
   e.hp=Math.max(0,e.hp-18);e.flash=.2;shake=3;
   for(let i=0;i<6;i++)particles.push({x:e.x,y:e.y-25,vx:(Math.random()-.5)*100,vy:-80-Math.random()*80,t:.45,color:'#9dfffa'});
   if(e.hp===0){player.gold+=e.boss?100:25;player.hp=Math.min(100,player.hp+12);if(e.boss){if(boarding)finishBoarding(true);else completeIsland();return;}notify('Whirlwind defeated a guard. +25 gold · +12 health',2);}
  }
 }
}
function updateWhirlwindHud(){if(!player)return;const cool=player.windCool||0,label=cool>0?'K · '+Math.ceil(cool)+'s':'K · WHIRLWIND';$('wind-status').textContent=label;$('whirlwind').disabled=cool>0||player.sp<40;$('whirlwind').innerHTML=(cool>0?Math.ceil(cool)+'s':'K')+'<span>WHIRLWIND</span>';}
function drawWhirlwind(){
 if(!player.wind)return;const p=screen(player.x,player.y),elapsed=1.1-player.wind,fade=Math.min(1,elapsed/.1,player.wind/.2);
 ctx.save();ctx.translate(p.x,p.y);ctx.scale(scale,scale);ctx.globalCompositeOperation='source-over';ctx.lineCap='round';ctx.shadowColor='#007da9';ctx.shadowBlur=10;
 for(let band=0;band<7;band++){
  const radius=60+band*13,phase=elapsed*11+band*.9;ctx.beginPath();ctx.strokeStyle='#087ba6';ctx.globalAlpha=fade*.85;ctx.lineWidth=band%2?12:16;
  for(let i=0;i<=50;i++){const a=phase+i/50*Math.PI*1.55,x=Math.cos(a)*radius,y=Math.sin(a)*radius*.38-band*9-8;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();ctx.strokeStyle=band%2?'#d7ffff':'#69f2ff';ctx.globalAlpha=fade;ctx.lineWidth=band%2?6:9;ctx.shadowColor='#7fffff';ctx.shadowBlur=18;ctx.stroke();ctx.strokeStyle='#ffffff';ctx.lineWidth=2;ctx.stroke();
 }
 ctx.shadowBlur=7;for(let i=0;i<24;i++){const a=elapsed*13+i*2.4,r=50+(i%7)*13;ctx.globalAlpha=fade*.8;ctx.fillStyle=i%2?'#e6ffff':'#9a91ff';ctx.beginPath();ctx.arc(Math.cos(a)*r,Math.sin(a)*r*.4-15-(i%5)*14,2.5+i%3,0,Math.PI*2);ctx.fill();}ctx.restore();
}
