'use strict';
let naval=null,navalFrame=0,navalLast=0,navalKeys=new Set(),navalStick={x:0,y:0},navalPointer=null,navalAim=null,navalHeld=false;
const navalCanvas=document.getElementById('naval-canvas'),navalCtx=navalCanvas.getContext('2d');
function startNavalBattle(){
 if(!voyage)return;cancelAnimationFrame(voyageFrame);cancelAnimationFrame(navalFrame);paused=true;keys.clear();navalKeys.clear();resetNavalStick();navalAim=null;navalHeld=false;
 document.getElementById('voyage').hidden=true;document.getElementById('naval').hidden=false;document.getElementById('naval-result').hidden=true;
 const rect=navalCanvas.getBoundingClientRect(),height=Math.max(600,1000*rect.height/Math.max(1,rect.width));
 const count=Math.max(1,Math.min(3,voyage.to));naval={width:1000,height,player:{x:500,y:height*.76,hp:160,max:160,angle:-Math.PI/2,cool:0,vx:0,vy:0,boost:0,boostCool:0},enemies:Array.from({length:count},(_,i)=>({x:(i+1)*1000/(count+1),y:height*.23,hp:90,max:90,angle:Math.PI/2,cool:1.6+i*.7})),shots:[],bursts:[],result:null,time:0,wave:1,sunk:0,intermission:0,shake:0};
 document.getElementById('naval-heading').textContent='Pirates block the passage';document.getElementById('naval-destination').textContent='Passage to '+islands[voyage.to].name;if(!voyage.arena&&voyage.to===3){Object.assign(naval.enemies[naval.enemies.length-1],{boss:true,hp:300,max:300});}if(voyage.arena){naval.enemies=navalFleet(1);document.getElementById('naval-heading').textContent='Open-water battle';document.getElementById('naval-destination').textContent='SURVIVE THREE WAVES';}resizeNaval();updateNavalHud();navalLast=0;navalFrame=requestAnimationFrame(navalLoop);navalCanvas.focus();
}
function resizeNaval(){if(!naval)return;const r=navalCanvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);navalCanvas.width=r.width*d;navalCanvas.height=r.height*d;navalCtx.setTransform(d,0,0,d,0,0);}
function resetNavalStick(){navalStick={x:0,y:0};navalPointer=null;document.getElementById('naval-stick').style.transform='';}
function navalFire(){
 if(!naval||naval.result||boarding||document.hidden||naval.player.cool>0)return;const p=naval.player,targets=naval.enemies.filter(e=>e.hp>0&&!e.disabled);if(!targets.length)return;
 const target=targets.reduce((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)<Math.hypot(b.x-p.x,b.y-p.y)?a:b),a=Math.atan2((navalAim||target).y-p.y,(navalAim||target).x-p.x);
 naval.shots.push({x:p.x+Math.cos(a)*38,y:p.y+Math.sin(a)*38,vx:Math.cos(a)*410,vy:Math.sin(a)*410,enemy:false,life:5});p.cool=.55;naval.bursts.push({x:p.x+Math.cos(a)*40,y:p.y+Math.sin(a)*40,life:.16,max:.16,hit:false});
}
function navalBurst(x,y,hit=true){naval.bursts.push({x,y,life:hit?.5:.3,max:hit?.5:.3,hit});}
function updateNaval(dt){
 if(!naval||naval.result||boarding||document.hidden)return;const n=naval,p=n.player;n.time+=dt;n.shake=Math.max(0,n.shake-dt);p.boost=Math.max(0,p.boost-dt);p.boostCool=Math.max(0,p.boostCool-dt);if(navalKeys.has('shift'))navalBoost();p.cool=Math.max(0,p.cool-dt);
 let x=(navalKeys.has('d')||navalKeys.has('arrowright')?1:0)-(navalKeys.has('a')||navalKeys.has('arrowleft')?1:0)+navalStick.x,y=(navalKeys.has('s')||navalKeys.has('arrowdown')?1:0)-(navalKeys.has('w')||navalKeys.has('arrowup')?1:0)+navalStick.y,m=Math.hypot(x,y);
 if(m>.08){x/=Math.max(1,m);y/=Math.max(1,m);const desired=Math.atan2(y,x);p.angle+=Math.atan2(Math.sin(desired-p.angle),Math.cos(desired-p.angle))*Math.min(1,dt*3.2);}else{x=0;y=0;}
 const speed=p.boost>0?340:190,blend=1-Math.exp(-dt*3);p.vx+=(x*speed-p.vx)*blend;p.vy+=(y*speed-p.vy)*blend;p.x+=p.vx*dt;p.y+=p.vy*dt;
 p.x=Math.max(50,Math.min(950,p.x));p.y=Math.max(60,Math.min(n.height-70,p.y));if(navalHeld||navalKeys.has('j')||navalKeys.has(' '))navalFire();
 for(const e of n.enemies){if(e.hp<=0||e.disabled)continue;let dx=p.x-e.x,dy=p.y-e.y,d=Math.max(1,Math.hypot(dx,dy));let mx=dx/d,my=dy/d;if(d<270){mx=-dy/d*.8;my=dx/d*.8;}e.x=Math.max(55,Math.min(945,e.x+mx*dt*62));e.y=Math.max(60,Math.min(n.height-65,e.y+my*dt*62));const desired=Math.atan2(my,mx);e.angle+=Math.atan2(Math.sin(desired-e.angle),Math.cos(desired-e.angle))*Math.min(1,dt*4);e.cool-=dt;if(e.cool<.8&&!e.aim)e.aim={x:p.x,y:p.y};if(e.cool<=0){const a=Math.atan2((e.aim||p).y-e.y,(e.aim||p).x-e.x);n.shots.push({x:e.x+Math.cos(a)*42,y:e.y+Math.sin(a)*42,vx:Math.cos(a)*235,vy:Math.sin(a)*235,enemy:true,life:7});e.cool=2.1+Math.random()*.7;e.aim=null;navalBurst(e.x,e.y,false);}if(d<66){p.x+=dx/d*dt*70;p.y+=dy/d*dt*70;}}
 for(const shot of n.shots){shot.life-=dt;shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;if(shot.life<=0)continue;if(shot.enemy){if(Math.hypot(shot.x-p.x,shot.y-p.y)<31){p.hp=Math.max(0,p.hp-14);n.shake=.25;shot.life=0;navalBurst(shot.x,shot.y);}}else for(const e of n.enemies){if(e.hp>0&&Math.hypot(shot.x-e.x,shot.y-e.y)<36){e.hp=Math.max(e.boss?e.max*.3:0,e.hp-30);if(e.boss&&e.hp<=e.max*.3){e.disabled=true;e.aim=null;}if(e.hp===0)n.sunk++;shot.life=0;navalBurst(shot.x,shot.y);break;}}}
 n.shots=n.shots.filter(s=>s.life>0&&s.x>-50&&s.x<1050&&s.y>-50&&s.y<n.height+50);for(const b of n.bursts)b.life-=dt;n.bursts=n.bursts.filter(b=>b.life>0);updateNavalHud();if(navalKeys.has('e'))tryBoardShip();
 if(p.hp<=0)endNavalBattle(false);else if(n.enemies.every(e=>e.hp<=0)){if(voyage.arena&&n.wave<3){if(!n.intermission){n.intermission=2;n.shots=[];p.hp=Math.min(p.max,p.hp+25);}n.intermission-=dt;if(n.intermission<=0){n.wave++;n.enemies=navalFleet(n.wave);n.intermission=0;}}else endNavalBattle(true);}
}
function updateNavalHud(){if(!naval)return;const flagship=naval.enemies.find(e=>e.boss&&e.hp>0),button=document.getElementById('board-ship');button.hidden=!flagship||!flagship.disabled;button.disabled=!canBoardShip();button.textContent=naval.enemies.some(e=>!e.boss&&e.hp>0)?'Defeat escorts to board':canBoardShip()?'Board Ship · E':'Sail closer to board';if(flagship)document.getElementById('naval-heading').textContent=flagship.disabled?'Flagship disabled — prepare to board':'Blackwake’s flagship · Weaken hull to 30%';document.getElementById('naval-boost').textContent=naval.player.boostCool>0?'Boost '+Math.ceil(naval.player.boostCool)+'s':'Full sail ⇧';document.getElementById('naval-boost').disabled=naval.player.boostCool>0||!!naval.result;document.getElementById('hull-fill').style.width=naval.player.hp/naval.player.max*100+'%';document.getElementById('hull-value').textContent=Math.ceil(naval.player.hp)+' / '+naval.player.max;document.getElementById('fleet-count').textContent=(voyage.arena?'Wave '+naval.wave+' / 3 · ':'')+naval.enemies.filter(e=>e.hp>0).length+' ships · '+naval.sunk+' sunk';document.getElementById('cannon-ready').textContent=naval.intermission?'Hull repaired +25 · Next wave…':naval.player.cool>0?'Reloading…':'Cannons ready';}
function drawNavalShip(ship,enemy){if(ship.hp<=0)return;const c=navalCtx;c.save();c.translate(ship.x,ship.y);c.rotate(ship.angle+Math.PI/2);if(ship.boss)c.scale(1.5,1.5);c.globalAlpha=.32;c.strokeStyle='#d9f6f3';c.lineWidth=4;c.beginPath();c.moveTo(-16,48);c.lineTo(-27,83+Math.sin(naval.time*4)*4);c.moveTo(16,48);c.lineTo(27,83);c.stroke();c.globalAlpha=1;c.drawImage(images[enemy?'enemy_ship':'player_ship'],-52,-64,104,128);c.restore();if(ship.boss){c.font='bold 16px sans-serif';c.textAlign='center';c.fillStyle=ship.disabled?'#ffe499':'#ffffff';c.fillText(ship.disabled?'BOARD · E':'BLACKWAKE',ship.x,ship.y-116);if(ship.disabled){c.strokeStyle='#ffe499';c.lineWidth=3;c.beginPath();c.arc(ship.x,ship.y,135,0,Math.PI*2);c.stroke();}}if(enemy){c.fillStyle='#061e2b';c.fillRect(ship.x-36,ship.y-75,72,6);c.fillStyle='#f47f63';c.fillRect(ship.x-36,ship.y-75,72*ship.hp/ship.max,6);}}
function renderNaval(){if(!naval)return;const c=navalCtx,r=navalCanvas.getBoundingClientRect();c.clearRect(0,0,r.width,r.height);c.save();c.scale(r.width/naval.width,r.height/naval.height);c.drawImage(images.battle_ocean,0,0,naval.width,naval.height);if(naval.shake>0)c.translate(Math.sin(naval.time*90)*4,Math.cos(naval.time*70)*4);for(const e of naval.enemies){if(e.hp>0&&e.aim){c.strokeStyle='#ff9274';c.lineWidth=3;c.setLineDash([10,10]);c.beginPath();c.moveTo(e.x,e.y);c.lineTo(e.aim.x,e.aim.y);c.stroke();c.setLineDash([]);}}if(navalAim){c.strokeStyle='#fff2bd';c.lineWidth=2;c.beginPath();c.arc(navalAim.x,navalAim.y,16,0,Math.PI*2);c.moveTo(navalAim.x-23,navalAim.y);c.lineTo(navalAim.x+23,navalAim.y);c.moveTo(navalAim.x,navalAim.y-23);c.lineTo(navalAim.x,navalAim.y+23);c.stroke();}for(const e of naval.enemies)drawNavalShip(e,true);drawNavalShip(naval.player,false);for(const s of naval.shots){c.fillStyle=s.enemy?'#ff774f':'#fff0b5';c.strokeStyle=s.enemy?'#8a291b':'#ac7a3c';c.lineWidth=2;c.beginPath();c.arc(s.x,s.y,s.enemy?7:6,0,Math.PI*2);c.fill();c.stroke();}for(const b of naval.bursts){const t=1-b.life/b.max;c.globalAlpha=1-t;c.strokeStyle=b.hit?'#ffd489':'#fff5d1';c.lineWidth=5;c.beginPath();c.arc(b.x,b.y,10+t*40,0,Math.PI*2);c.stroke();}c.restore();}
function navalLoop(ts){if(!naval)return;const dt=Math.min(.035,(ts-navalLast)/1000||.016);navalLast=ts;if(!boarding){updateNaval(dt);renderNaval();}navalFrame=requestAnimationFrame(navalLoop);}
function endNavalBattle(won){if(!naval||naval.result)return;naval.result=won?'won':'lost';navalKeys.clear();resetNavalStick();document.getElementById('naval-result').hidden=false;document.getElementById('naval-result-title').textContent=won?'The passage is clear.':'Your ship was sunk.';document.getElementById('naval-result-text').textContent=won?'The enemy fleet is defeated. Continue your voyage to '+islands[voyage.to].name+'.':'Retry the sea battle or return to the sea chart.';document.getElementById('naval-continue').textContent=won?'Continue voyage':'Retry battle';if(voyage.arena){document.getElementById('naval-result-title').textContent=won?'You command these waters.':'Your ship was sunk.';document.getElementById('naval-result-text').textContent=(naval.captured?'Flagship captured · ':'')+naval.sunk+' ships sunk · Wave '+naval.wave+' of 3 · '+Math.round(naval.time)+' seconds at sea.';document.getElementById('naval-continue').textContent=won?'Battle again':'Retry battle';}document.getElementById('naval-continue').focus();}
function continueNaval(){if(!naval||!naval.result)return;if(voyage.arena||naval.result==='lost'){startNavalBattle();return;}cancelAnimationFrame(navalFrame);naval=null;voyage.battleCleared=true;voyage.resumeAt=.48;voyage.started=null;document.getElementById('naval').hidden=true;document.getElementById('voyage').hidden=false;voyageFrame=requestAnimationFrame(animateVoyage);}
function leaveNaval(){cancelAnimationFrame(navalFrame);naval=null;voyage=null;navalKeys.clear();resetNavalStick();document.getElementById('naval').hidden=true;document.getElementById('voyage').hidden=true;openCampaign();}
addEventListener('resize',resizeNaval);addEventListener('blur',()=>{navalKeys.clear();navalHeld=false;resetNavalStick();});
addEventListener('keydown',e=>{if(!naval||boarding)return;const key=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright','j','w','a','s','d','shift','e'].includes(key))e.preventDefault();navalKeys.add(key);});addEventListener('keyup',e=>navalKeys.delete(e.key.toLowerCase()));
const navalJoy=document.getElementById('naval-joystick');function moveNavalStick(e){if(e.pointerId!==navalPointer)return;const r=navalJoy.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,m=Math.max(36,Math.hypot(x,y));navalStick={x:x/m,y:y/m};document.getElementById('naval-stick').style.transform=`translate(${navalStick.x*32}px,${navalStick.y*32}px)`;}navalJoy.onpointerdown=e=>{navalPointer=e.pointerId;navalJoy.setPointerCapture(e.pointerId);moveNavalStick(e)};navalJoy.onpointermove=moveNavalStick;navalJoy.onpointerup=resetNavalStick;navalJoy.onpointercancel=resetNavalStick;
document.getElementById('fire-cannon').onpointerdown=e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);navalHeld=true;navalAim=null;navalFire()};document.getElementById('fire-cannon').onpointerup=()=>navalHeld=false;document.getElementById('fire-cannon').onpointercancel=()=>navalHeld=false;document.getElementById('naval-continue').onclick=continueNaval;document.getElementById('naval-retreat').onclick=leaveNaval;

function navalFleet(wave){return Array.from({length:wave},(_,i)=>({x:(i+1)*1000/(wave+1),y:naval.height*.2,hp:wave===3&&i===2?300:90+(wave-1)*30,max:wave===3&&i===2?300:90+(wave-1)*30,boss:wave===3&&i===2,angle:Math.PI/2,cool:1.8+i*.8}));}
function startBoatMode(){if(!player||voyage)return;document.getElementById('campaign').hidden=true;document.getElementById('overlay').hidden=true;joyEnd();voyage={from:currentLevel,to:currentLevel,arena:true};startNavalBattle();}
function navalBoost(){if(!naval||naval.result||boarding||naval.player.boostCool>0)return;naval.player.boost=1.1;naval.player.boostCool=5;}
navalCanvas.onpointermove=e=>{if(e.pointerType==='touch'||!naval)return;const r=navalCanvas.getBoundingClientRect();navalAim={x:(e.clientX-r.left)/r.width*naval.width,y:(e.clientY-r.top)/r.height*naval.height};};
navalCanvas.onpointerdown=e=>{if(e.pointerType==='touch')return;navalCanvas.onpointermove(e);navalHeld=true;navalCanvas.setPointerCapture(e.pointerId);navalFire();};
navalCanvas.onpointerup=()=>navalHeld=false;navalCanvas.onpointercancel=()=>navalHeld=false;navalCanvas.onpointerleave=()=>{if(!navalHeld)navalAim=null;};
document.getElementById('boat-mode').onclick=startBoatMode;document.getElementById('chart-boat-mode').onclick=startBoatMode;
document.getElementById('naval-exit').onclick=leaveNaval;document.getElementById('naval-boost').onclick=navalBoost;

function canBoardShip(){if(!naval||naval.result||boarding)return false;const boss=naval.enemies.find(e=>e.boss&&e.disabled&&e.hp>0);return !!boss&&!naval.enemies.some(e=>!e.boss&&e.hp>0)&&Math.hypot(boss.x-naval.player.x,boss.y-naval.player.y)<150;}
function tryBoardShip(){if(canBoardShip())startBoarding();}
document.getElementById('board-ship').onclick=tryBoardShip;
